//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_Company
    {
        public Cars_Company()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public int Company_no { get; set; }
        public string Company_nm { get; set; }
    
        public virtual ICollection<Cars> Cars { get; set; }
    }
}
