//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsManage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HB_GlobalEntities : DbContext
    {
        public HB_GlobalEntities()
            : base("name=HB_GlobalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cars_Brand> Cars_Brand { get; set; }
        public virtual DbSet<Cars_Gas> Cars_Gas { get; set; }
        public virtual DbSet<Cars_Insurance> Cars_Insurance { get; set; }
        public virtual DbSet<Cars_State> Cars_State { get; set; }
        public virtual DbSet<Dlv_Center> Dlv_Center { get; set; }
        public virtual DbSet<Insurance> Insurance { get; set; }
        public virtual DbSet<Insurance_Company> Insurance_Company { get; set; }
        public virtual DbSet<Cars_Company> Cars_Company { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
    }
}
