//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_Insurance
    {
        public Cars_Insurance()
        {
            this.Insurance = new HashSet<Insurance>();
        }
    
        public int Uid { get; set; }
        public int Car_Uid { get; set; }
        public int Company_no { get; set; }
        public string Insurance_no { get; set; }
        public string Card_no { get; set; }
        public Nullable<System.DateTime> Date_S { get; set; }
        public Nullable<System.DateTime> Date_E { get; set; }
        public string Remark { get; set; }
    
        public virtual Insurance_Company Insurance_Company { get; set; }
        public virtual ICollection<Insurance> Insurance { get; set; }
        public virtual Cars Cars { get; set; }
    }
}
