//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dlv_Center
    {
        public Dlv_Center()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public string Center_no { get; set; }
        public string Center_nm { get; set; }
        public string Addr { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string Dsp_sw { get; set; }
    
        public virtual ICollection<Cars> Cars { get; set; }
    }
}
