//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public int Uid { get; set; }
        public int Insurance_Uid { get; set; }
        public string Insurance_no { get; set; }
        public string Insurance_nm { get; set; }
        public Nullable<decimal> Insurance_Money { get; set; }
        public Nullable<decimal> Self_Money { get; set; }
        public Nullable<decimal> Pay_Money { get; set; }
        public string Remark { get; set; }
    
        public virtual Cars_Insurance Cars_Insurance { get; set; }
    }
}
